#!/usr/bin/env node
/**
 * Generates TypeScript types from ASP JSON Schemas.
 *
 * Uses a custom $ref resolver so that:
 *   - Relative ./schemas/... refs  →  reads from local spec/schemas/...
 *   - https://ucp.dev/schemas/...  →  fetched normally (site is live)
 *
 * No schema files are modified; the canonical URLs stay as-is.
 */

import { compileFromFile } from "json-schema-to-typescript";
import { readdir, readFile, writeFile, mkdir } from "node:fs/promises";
import { join, resolve, relative, dirname } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const SCHEMA_DIR = join(ROOT, "spec", "schemas");
const OUT_FILE = join(ROOT, "generated", "types.ts");

// Workaround: ucp.dev/ucp.json references "https://ucp.dev/services/service.json"
// but the correct URL is "https://ucp.dev/schemas/service.json". Redirect it.
const UCP_URL_FIXES = {
  "https://ucp.dev/services/service.json":
    "https://ucp.dev/schemas/service.json",
};

// Custom resolver: patches known-broken ucp.dev URLs.
// All other ucp.dev URLs resolve via HTTP.
const aspResolver = {
  order: 1,
  canRead(file) {
    const url = typeof file === "string" ? file : file.url;
    return !!UCP_URL_FIXES[url];
  },
  async read(file) {
    const url = typeof file === "string" ? file : file.url;

    // Broken UCP URL → fetch the correct one
    const target = UCP_URL_FIXES[url];
    const resp = await fetch(target);
    if (!resp.ok) throw new Error(`HTTP ${resp.status} for ${target}`);
    return resp.text();
  },
};

const refOptions = {
  resolve: {
    asp: aspResolver,
  },
};

// Recursively collect all .json files
async function collectSchemas(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const files = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await collectSchemas(full)));
    } else if (entry.name.endsWith(".json")) {
      files.push(full);
    }
  }
  return files;
}

async function main() {
  const schemas = await collectSchemas(SCHEMA_DIR);
  console.log(`Found ${schemas.length} schema files`);

  const chunks = [];
  for (const file of schemas) {
    const rel = relative(SCHEMA_DIR, file);
    try {
      const ts = await compileFromFile(file, {
        cwd: dirname(file),
        $refOptions: refOptions,
        bannerComment: `/* Generated from ${rel} */`,
        unreachableDefinitions: true,
        declareExternallyReferenced: false,
        format: false,
      });
      chunks.push(ts);
      console.log(`  ✓ ${rel}`);
    } catch (err) {
      console.error(`  ✗ ${rel}: ${err.message}`);
    }
  }

  // Fix broken `extends` clauses from unresolved external $ref (e.g. UCP allOf)
  for (let i = 0; i < chunks.length; i++) {
    chunks[i] = chunks[i].replace(
      /export interface (\w+) extends\s+\{/g,
      "export interface $1 {",
    );
  }

  // Fix disambiguated type names (e.g. Image1 → Image) caused by
  // json-schema-to-typescript creating numbered variants when the same $ref
  // appears in both a direct property and an array items context.
  // These numbered types are never declared, leaving dangling references.
  for (let i = 0; i < chunks.length; i++) {
    chunks[i] = chunks[i].replace(/\b([A-Z][a-zA-Z]+?)(\d+)\b/g, (match, base, num) => {
      // Only fix if the base type name exists (was seen or is a known type)
      // and the numbered variant is NOT independently exported in this chunk
      if (chunks[i].includes(`export interface ${match}`) || chunks[i].includes(`export type ${match}`)) {
        return match; // It's a real, distinct type — leave it alone
      }
      return base;
    });
  }

  // Deduplicate: keep only the first occurrence of each exported declaration
  const seen = new Set();
  const dedupedChunks = [];
  for (const chunk of chunks) {
    const lines = chunk.split("\n");
    const filteredLines = [];
    let skip = false;
    for (let i = 0; i < lines.length; i++) {
      const exportMatch = lines[i].match(
        /^export\s+(?:interface|type|enum)\s+(\w+)/,
      );
      if (exportMatch) {
        const name = exportMatch[1];
        if (seen.has(name)) {
          // Skip until next export or banner comment or end
          skip = true;
          continue;
        }
        seen.add(name);
        skip = false;
      } else if (skip) {
        // Keep banner comments (start of next chunk section)
        if (lines[i].startsWith("/*") && lines[i].includes("Generated from")) {
          skip = false;
        } else {
          continue;
        }
      }
      filteredLines.push(lines[i]);
    }
    dedupedChunks.push(filteredLines.join("\n"));
  }

  await mkdir(join(ROOT, "generated"), { recursive: true });
  const banner = "/* Auto-generated by scripts/generate-types.mjs — do not edit */\n\n";
  await writeFile(OUT_FILE, banner + dedupedChunks.join("\n"), "utf-8");
  console.log(`\nWrote ${OUT_FILE}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
